version: "2.1"
services:
  webtop:
    image: undaacid/ubuntu20_04:latest
    container_name: CloudPC
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - SUBFOLDER=/ #optional
      - KEYBOARD=en-us-qwerty #optional
      - TITLE=CloudPC #optional
    volumes:
      - /config/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3002:3000
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
